name: Release from Merged PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: changelog
        uses: mikepenz/release-changelog-generator@v1
        with:
          # This action will automatically categorize your commits.
          # The template defines how the changelog is formatted.
          # You can remove this for a more basic template.
          template: "## What's Changed\n\n{{#with groups}}\n\n{{#if features}}### ✨ Features\n{{#each features}}* {{this.body}} ({{this.author.login}})\n{{/each}}{{/if}}\n\n{{#if fixes}}### 🐛 Bug Fixes\n{{#each fixes}}* {{this.body}} ({{this.author.login}})\n{{/each}}{{/if}}\n\n{{#if changes}}### 🛠️ Maintenance\n{{#each changes}}* {{this.body}} ({{this.author.login}})\n{{/each}}{{/if}}\n\n{{/with}}\n\n{{#each unparsed_commits}}* {{this.body}} ({{this.author.login}})\n{{/each}}\n\n**Full Changelog**: https://github.com/{{ owner }}/{{ repository }}/compare/{{ tag_name }}...{{ new_tag_name }}"

      - name: Create release tag
        id: create_tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ github.run_number }}"
          name: "Release ${{ github.event.pull_request.title }}"
          body: ${{ steps.changelog.outputs.changelog }}
